sudo: required

language: python

services:
  - docker

cache:
  directories:
  - $HOME/docker

before_install:
  - docker build -t lahirs2/vicious-machines:latest .
  - docker run -d --name vicious-app -p 5000:5000 lahirs2/vicious-machines:latest

script:
  - docker exec vicious-app python -m unittest discover

after_script:
  - docker rm -f vicious-app

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f120f1c05d5db8ec9bf
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always